on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  check-stale-repos:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: docker://ghcr.io/github/stale_repos:v1
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ORGANIZATION: italia
        INACTIVE_DAYS: 365

    - name: Check for the stale report issue
      id: existing_issue
      run: |
        ISSUE_NUMBER=$(gh search issues "Stale repository report" --label "stale-report" --match title --json number --jq ".[0].number")
        echo "issue_number=$ISSUE_NUMBER" >> "$GITHUB_ENV"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: peter-evans/create-issue-from-file@v4
      with:
        issue-number: ${{ env.issue_number }}
        title: Stale repository report
        content-filepath: ./stale_repos.md
        labels: stale-report
        token: ${{ secrets.GITHUB_TOKEN }}
